# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('base_pay', models.FloatField(blank=True, null=True)),
                ('overtime_pay', models.FloatField(blank=True, null=True)),
                ('other_pay', models.FloatField(blank=True, null=True)),
                ('benefits', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
    ]
